### PR TITLE
Add PostgreSQL 10.6 + PostGIS 2.5 to build matrix

### LINKED ISSUE #14: Create PostgreSQL 10.6 container image
Similar to https://github.com/azavea/docker-postgis/pull/13, add PostgreSQL version 10.6 to the build matrix and note the PostGIS version that gets installed along with it.

### PR DESCRIPTION
**Pull request by CloudNiner**
I updated the README with the newest build combination like last time for 10.3 since that seems like what we've been doing. Happy to revert if desired.

I discovered the correct version of PostGIS by running `docker run -it --rm postgis:10.6 /bin/bash` and then executing a `apt-get update && apt-cache policy postgis` within the bash shell on the postgres container. Options were 2.5 or 2.3 and I went with the newer version.

Closes #14

### CODE REVIEW

**Comment by CloudNiner** [comment]
The build failed because of an invalid POSTGIS_VERSION for every entry in the matrix before the 10.6 one that was just added.

`apt-cache policy` on the `postgres:10.3` container results in:
```
root@a9d739f60677:/# apt-cache policy postgresql
postgresql:
  Installed: (none)
  Candidate: 11+197.pgdg90+1
  Version table:
     11+197.pgdg90+1 500
        500 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
     9.6+181+deb9u2 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
     9.6+181+deb9u1 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
```
Note that there is no entry for PostGIS 2.4.

Similar issues exist for some of the other combinations and we wouldn't want to change the POSTGIS_VERSION string and push new containers unless the major+minor+fix versions all match.

Perhaps there's a better way to get a list of the available version strings? I had trouble finding a more complete list (if it exists) via the PostgreSQL APT repo at http://apt.postgresql.org/pub/repos/apt/ and https://wiki.postgresql.org/wiki/Apt

**Comment by hectcastro** [comment]
If you're not blocked by this (likely able to use 10.3, if you're messing with the local Tegola stuff), we can queue this up for next sprint or the end of this one to resolve.

**Comment by rbreslow** [comment]
@CloudNiner A more complete list of available packages for Stretch might be:

http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages

No action needed, just saw your comment. Working on getting this PR to pass as part of #14.

**Comment by hectcastro** [comment]
It might be worth considering just closing this PR because Amazon RDS only appears to support PostGIS 2.4 on PostgreSQL 10.x: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html

That shouldn't necessarily limit us from publishing a PostgreSQL 10.x/PostGIS 2.5.x combo, but it is at least one reason not to. We already have a PostgreSQL 10.6.x/PostGIS 2.4.x combo.

**Comment by CloudNiner** [comment]
Let's avoid publishing it until we have a use case for it ourselves or an external contributor requests it. While it wouldn't take a ton of time to correct if a developer spun up a new project with an unsupported Postgres/PostGIS combo on RDS, it's something else for the developer to consider. I know generally when we start new projects we default to choosing the latest available versions and it would be an easy mistake to make.

If we get to the point where we want to build the 10.6/2.5 combo we can add a README table that indicates RDS support for each combination. Looks like Postgres 11 is matched with PostGIS 2.5 for RDS.

**Comment by CloudNiner** [comment]
In any case @rbreslow no worries on the double mention, thanks for tackling this set of updates for us.

**Pull request closed without merging**
