### PR TITLE
Bump version in postgresql.conf

### PR DESCRIPTION
**Pull request by sharph**
I missed this.

### CODE REVIEW

**Comment by hectcastro** [comment]
👍 

Before cutting the next release, see if you can create one for `5.3.3` vs. `0.2.0` or `0.3.0` like https://github.com/azavea/docker-django/blob/develop/CHANGELOG.md.

**Comment by sharph** [comment]
Sure, I prefer that as well.

**Comment by sharph** [comment]
`5.3.3` or `9.5.3`?

**Comment by hectcastro** [comment]
The latter. That's a typo.

**Pull request merged**
